#!/usr/bin/php
<?php
include("extensions/sync.php");
define("CONFIG_FILE_NAME", "CONFIG");
define("XML_MODE_ATTRIBUTE", 0);
define("XML_MODE_NODE", 1);

if ( 1 == $argc ) {
	exitWithError("usage: " . $argv[0] . " [work | play]");
}

$whoami = trim(strtolower(`whoami`));

if ( 'root' != strtolower($whoami) ) {
	exitWithError("Please run script as root.");
}

$siteList = array(
	'reddit.com', 'forums.somethingawful.com', 'somethingawful.com',
	'digg.com', 'break.com', 'news.ycombinator.com',
	'infoq.com', 'bebo.com', 'twitter.com',
	'facebook.com', 'blip.com', 'youtube.com',
	'vimeo.com', 'delicious.com', 'flickr.com',
	'friendster.com', 'hi5.com', 'linkedin.com',
	'livejournal.com', 'meetup.com', 'myspace.com',
	'plurk.com', 'stickam.com', 'stumbleupon.com',
	'yelp.com', 'slashdot.com'
);

/*
Pinboard.in syncing -- set $tag to tag of sites to be blocked

On application run you will need to specify password with -p password OR store in CONFIG file.
*/
$remote_apps = array("pinboard_in");
$remote_creds = array();

# Include config
if (file_exists(CONFIG_FILE_NAME)) include(CONFIG_FILE_NAME);

foreach ($remote_apps as $app) { 
  # Include apps
  include("extensions/$app.php");
  
  # Sync apps
  $array = sync($app, $remote_apps[$app]);
  foreach ($array as $site) {
    if (!in_array($site, $siteList)) {
      $siteList[] = $site;
    }
  }
}

$restartNetworkingCommand = 'ifconfig en0 down; ifconfig en0 up';
$hostsFile = '/etc/hosts';
$startToken = '## start-gsd';
$endToken = '## end-gsd';

$action = $argv[1];

switch ( $action ) {
	case 'work': {
		$fh = fopen($hostsFile, 'a');
		if ( false === $fh ) {
			exitWithError("Failed to open the hosts file.");
		}
		
		fwrite($fh, $startToken . PHP_EOL);
		foreach ( $siteList as $site ) {
			fwrite($fh, "127.0.0.1\t{$site}" . PHP_EOL);
			fwrite($fh, "127.0.0.1\twww.{$site}" . PHP_EOL);
		}
		fwrite($fh, $endToken . PHP_EOL);
		
		fclose($fh);
		
		shell_exec($restartNetworkingCommand);
		
		print "\r\nFinished.\r\n" .
		      count($siteList) . " domains blocked.\r\n" .
		      "Hope you enjoyed your time off, now go be a super-productive hero. GET TO WORK, BITCH!\r\n";
		
		break;
	}
	
	case 'play': {
		$hostContents = file($hostsFile);
		if ( false === $hostContents ) {
			exitWithError("Failed to open the hosts file.");
		}
		
		$startIndex = -1;
		for ( $i=0; $i<count($hostContents); $i++ ) {
			if ( trim($hostContents[$i]) == $startToken ) {
				$startIndex = $i;
			}
		}
		
		if ( $startIndex > -1 ) {
			$hostContents = array_slice($hostContents, 0, $startIndex);
			file_put_contents($hostsFile, $hostContents);
			shell_exec($restartNetworkingCommand);
		}
		
		print "\r\nFinished.\r\n" .
		      count($siteList) . " domains now accessible.\r\n" .
		      "Enjoy playing!\r\n";
				
		break;
	}
}

function exitWithError($error) {
	fwrite(STDERR, $error . PHP_EOL);
	exit(1);
}
